using System;
using System.Drawing;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.NetworkInformation;
using System.Net.Sockets;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;

partial class ThebestRGB {
 TcpListener mobileListener;CancellationTokenSource mobileStop;string mobileAddress="";
 void StartMobileRemote(){
  try{
   EnsureMobileFirewallRule();
   IPAddress address=Dns.GetHostEntry(Dns.GetHostName()).AddressList.FirstOrDefault(a=>a.AddressFamily==AddressFamily.InterNetwork&&!IPAddress.IsLoopback(a));string ip=address==null?null:address.ToString();
   if(string.IsNullOrEmpty(ip))return;
   mobileAddress="http://"+ip+":18765/";mobileListener=new TcpListener(IPAddress.Any,18765);mobileListener.Start();mobileStop=new CancellationTokenSource();Task.Run(()=>MobileLoop(mobileStop.Token));
  }catch{mobileAddress="";}
 }
 void EnsureMobileFirewallRule(){try{using(var command=Process.Start(new ProcessStartInfo("netsh","advfirewall firewall add rule name=\"ThebestRGB controle pelo celular\" dir=in action=allow protocol=TCP localport=18765 profile=any remoteip=localsubnet"){UseShellExecute=false,CreateNoWindow=true})){command.WaitForExit(3000);}}catch{}}
 string MobileAddresses(){return string.Join("\r\n",NetworkInterface.GetAllNetworkInterfaces().Where(n=>n.OperationalStatus==OperationalStatus.Up).SelectMany(n=>n.GetIPProperties().UnicastAddresses).Where(a=>a.Address.AddressFamily==AddressFamily.InterNetwork&&!IPAddress.IsLoopback(a.Address)).Select(a=>"http://"+a.Address+":18765/").Distinct().ToArray());}
 async Task MobileLoop(CancellationToken token){try{while(!token.IsCancellationRequested){TcpClient client;try{client=await mobileListener.AcceptTcpClientAsync();}catch{break;}Task.Run(()=>MobileRequest(client));}}catch{}}
 void MobileRequest(TcpClient client){using(client)try{NetworkStream stream=client.GetStream();var reader=new StreamReader(stream,Encoding.ASCII);string first=reader.ReadLine();if(string.IsNullOrEmpty(first)){return;}string[] parts=first.Split(' ');string resource=parts.Length>1?parts[1]:"/";string line;while(!string.IsNullOrEmpty(line=reader.ReadLine())){}Uri uri=new Uri("http://local"+resource);if(uri.AbsolutePath.ToLowerInvariant()=="/set"){string hex=(Uri.UnescapeDataString(uri.Query).Replace("?color=","").Split('&')[0]??"").Trim().TrimStart('#');int value,mode;string modeText=uri.Query.Split('&').FirstOrDefault(x=>x.StartsWith("mode="));int.TryParse(modeText==null?"":modeText.Substring(5),out mode);if(hex.Length==6&&int.TryParse(hex,System.Globalization.NumberStyles.HexNumber,null,out value)){Color c=Color.FromArgb((value>>16)&255,(value>>8)&255,value&255);BeginInvoke(new Action(async delegate{if(busy)return;SetGlobal(c);if(mode>=0&&mode<EffectLibrary.Names.Length)effectMode.SelectedIndex=mode;await ApplyCards(cards.Where(card=>card.State.Included).ToList());}));WriteMobile(stream,"ok");}else WriteMobile(stream,"Cor inválida",400);return;}WriteMobile(stream,MobilePage(),200,"text/html; charset=utf-8");}catch{}}
 static void WriteMobile(NetworkStream stream,string body,int status=200,string type="text/plain; charset=utf-8"){byte[] bytes=Encoding.UTF8.GetBytes(body);string headers="HTTP/1.1 "+status+" OK\r\nContent-Type: "+type+"\r\nContent-Length: "+bytes.Length+"\r\nConnection: close\r\n\r\n";byte[] head=Encoding.ASCII.GetBytes(headers);stream.Write(head,0,head.Length);stream.Write(bytes,0,bytes.Length);}
 string MobilePage(){return @"<!doctype html><html><head><meta name='viewport' content='width=device-width,initial-scale=1'><style>body{margin:0;padding:24px;background:#101117;color:#fff;font:16px Segoe UI,Arial}main{max-width:420px;margin:auto}h1{margin:0 0 6px}p{color:#b9b2d4}.colors{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}button,input,select{box-sizing:border-box;width:100%;border:0;border-radius:10px;padding:16px;font:inherit}button{font-weight:700;color:#15111f;background:#9777f6}button.white{background:#fff;color:#111}button.red{background:#f22}button.blue{background:#42c8ff}button.green{background:#2ecf76}input,select{margin:12px 0;background:#252736;color:#fff}.note{font-size:13px}</style></head><body><main><h1>ThebestRGB</h1><p>Controle remoto do seu setup</p><div class='colors'><button class='white' onclick='go(&quot;ffffff&quot;)'>Branco</button><button class='red' onclick='go(&quot;ff0000&quot;)'>Vermelho</button><button class='blue' onclick='go(&quot;66d9ff&quot;)'>Azul-claro</button><button class='green' onclick='go(&quot;00ff00&quot;)'>Verde</button><button onclick='go(&quot;a060ff&quot;)'>Roxo</button><button onclick='go(&quot;ffaa20&quot;)'>Laranja</button></div><input id='color' value='#ffffff' maxlength='7'><select id='mode'><option value='0'>Cor fixa</option><option value='1'>Arco-íris</option><option value='2'>Respiração</option><option value='4'>Onda pelo setup</option><option value='16'>Elétrica</option><option value='17'>Áudio</option><option value='18'>Ambilight</option></select><button onclick='apply()'>Aplicar no setup</button><p class='note'>Funciona de qualquer rede enquanto o ThebestRGB estiver aberto.</p></main><script>function go(c){document.getElementById('color').value='#'+c;apply()}function apply(){let c=document.getElementById('color').value.replace('#',''),m=document.getElementById('mode').value;fetch('/set?color='+encodeURIComponent(c)+'&mode='+m).then(()=>{})}</script></body></html>";}
 void ShowMobileRemote(){if(string.IsNullOrEmpty(mobileAddress)){MessageBox.Show(this,"Não foi possível iniciar o controle pelo celular nesta rede.","ThebestRGB");return;}using(var dialog=new Form{Text="ThebestRGB / Controle pelo celular",ClientSize=new Size(510,218),BackColor=surface,ForeColor=Color.White,Font=new Font("Segoe UI",10),StartPosition=FormStartPosition.CenterParent,MaximizeBox=false,MinimizeBox=false}){dialog.Controls.Add(new Label{Text="No celular, conectado ao mesmo Wi-Fi, abra:",AutoSize=true,Location=new Point(24,34)});var address=new TextBox{ReadOnly=true,Multiline=true,Text=mobileAddress,BackColor=Color.FromArgb(35,38,50),ForeColor=Color.White,BorderStyle=BorderStyle.FixedSingle};address.SetBounds(24,65,462,50);dialog.Controls.Add(address);dialog.Controls.Add(new Label{Text="Funciona somente nesta rede. Mantenha o ThebestRGB aberto neste PC.",ForeColor=Muted,Size=new Size(462,28),Location=new Point(26,128)});var close=Button("Fechar",surface);close.DialogResult=DialogResult.OK;close.SetBounds(356,170,130,32);dialog.Controls.Add(close);dialog.AcceptButton=close;DarkDialogChrome.Attach(dialog,dialog.Text);dialog.ShowDialog(this);}}
 void StopMobileRemote(){try{if(mobileStop!=null)mobileStop.Cancel();if(mobileListener!=null)mobileListener.Stop();}catch{}}
}
