// SPDX-License-Identifier: GPL-2.0-or-later
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using Microsoft.Win32;

partial class ThebestRGB {
 Button resetSetup,testSelected,diagnostic;ToolStripMenuItem themeItem,startupItem;
 Dictionary<int,Color> lastSentColors=new Dictionary<int,Color>();
 Keys saveShortcut=Keys.Control|Keys.S,undoShortcut=Keys.Control|Keys.Z,verifyShortcut=Keys.F5,stopShortcut=Keys.Escape;
 Label shortcutHint;
 void InitializeMaxFeatures(){BrandMigration.Startup();
  resetSetup=Button("Iluminação predefinida",surface);resetSetup.Parent=main;resetSetup.Click+=async delegate{await RestoreAndApply();};
  testSelected=new AutoApplyButton{Text="Aplicação automática",BackColor=surface,ForeColor=Color.White,Font=new Font("Segoe UI",9),FlatStyle=FlatStyle.Flat,UseVisualStyleBackColor=false,FlatAppearance={BorderSize=0}};testSelected.Parent=main;InitializeAutoApply();
  diagnostic=Button("Diagnóstico",surface);diagnostic.Parent=side;diagnostic.Click+=delegate{ExportDiagnostics();};
  shortcutHint=new Label{Text="Ctrl+S salvar  ·  Ctrl+Z desfazer  ·  F5 verificar  ·  Esc parar",ForeColor=Muted,Font=new Font("Segoe UI",8),AutoEllipsis=true};main.Controls.Add(shortcutHint);
  themeItem=new ToolStripMenuItem("Tema claro"){CheckOnClick=true};themeItem.CheckedChanged+=delegate{ApplyTheme(themeItem.Checked);};
  startupItem=new ToolStripMenuItem("Iniciar com o Windows"){CheckOnClick=true,Checked=IsStartupEnabled()};startupItem.CheckedChanged+=delegate{SetStartup(startupItem.Checked);};trayMenu.Items.Add(startupItem);
  trayMenu.Items.Add("Configurar atalhos",null,delegate{ConfigureShortcuts();});
  KeyPreview=true;UpdateMaxState();Resize+=delegate{LayoutMaxFeatures();};Shown+=delegate{LayoutMaxFeatures();};
 }
 void LayoutMaxFeatures(){if(designReady){LayoutDesign();return;}if(resetSetup==null)return;int baseX=U(467);resetSetup.SetBounds(baseX,U(91),U(166),U(30));testSelected.SetBounds(baseX+U(178),U(91),U(236),U(30));diagnostic.SetBounds(U(16),U(main.ClientSize.Height<720?598:614),U(148),U(30));shortcutHint.SetBounds(U(24),U(654),Math.Max(U(300),main.ClientSize.Width-U(48)),U(20));shortcutHint.Visible=main.ClientSize.Height>=720;}
 void UpdateMaxState(){if(testSelected==null)return;testSelected.Enabled=!busy&&cards.Any(c=>c.State.Included);resetSetup.Enabled=!busy;diagnostic.Enabled=!busy;}
 string RestorePointFile{get{return startupRestorePath??Path.Combine(Path.GetDirectoryName(ProfileStore.FileName),"restore-point.json");}}
 void SaveRestorePoint(){try{Directory.CreateDirectory(Path.GetDirectoryName(RestorePointFile));File.WriteAllText(RestorePointFile,new System.Web.Script.Serialization.JavaScriptSerializer().Serialize(CaptureSetup()));LocalBackup.BackupFiles();status.Text="Setup salvo para restauração. Clique em Iluminação predefinida quando quiser voltar a ele.";}catch(Exception ex){status.Text="Não foi possível salvar o estado: "+ex.Message;}}
 void RestoreSavedSetup(){if(!File.Exists(RestorePointFile)){status.Text="Nenhum setup salvo para restauração. Salve o atual pelo menu Ferramentas.";return;}try{var s=ReadRestorePoint();if(s==null||s.Devices==null||s.Devices.Length!=4)throw new InvalidDataException();if(lastSetup!=null)undoStates.Push(lastSetup);restoringSetup=true;pendingBar=s.Bar==null?new KeyboardBarSettings():s.Bar.Copy();msiZones=s.MsiZones==null?new MsiZoneSettings():s.MsiZones.Copy();effectOptions=s.Options.Select(o=>o.Copy()).ToArray();effectMode.SelectedIndex=s.Mode;effectSpeed.Value=s.Speed;master.Value=s.Master;global=Color.FromArgb(s.Global);pick.BackColor=global;pick.ForeColor=global.GetBrightness()>.6?Color.Black:Color.White;hex.Text="#"+(s.Global&0xffffff).ToString("X6");profileName.Text=s.Profile??profileName.Text;for(int i=0;i<4;i++){cards[i].State=s.Devices[i].Copy();cards[i].State.Name=HardwareNames[i];cards[i].RefreshState(true);cards[i].Status.Text="Não aplicado";}restoringSetup=false;lastSetup=CaptureSetup();lastEdit=DateTime.MinValue;UpdateSelection();UpdateMaxState();status.Text="Setup salvo recuperado na prévia. Clique em Aplicar iluminação.";}catch(Exception ex){restoringSetup=false;status.Text="Não foi possível restaurar o estado salvo: "+ex.Message;}}
 void ResetSetup(){if(busy)return;if(lastSetup!=null)undoStates.Push(lastSetup);restoringSetup=true;try{pendingBar=new KeyboardBarSettings();msiZones=new MsiZoneSettings();effectOptions=EffectOptions.Defaults();effectMode.SelectedIndex=0;effectSpeed.Value=3;master.Value=100;global=Color.White;pick.BackColor=global;pick.ForeColor=Color.Black;hex.Text="#FFFFFF";for(int i=0;i<cards.Count;i++){cards[i].State.R=255;cards[i].State.G=255;cards[i].State.B=255;cards[i].State.Brightness=100;cards[i].State.Included=true;cards[i].RefreshState(true);cards[i].Status.Text="Não aplicado";connectionLabels[i].Text="Não verificado";connectionLabels[i].ForeColor=Muted;}}finally{restoringSetup=false;}lastSetup=CaptureSetup();lastEdit=DateTime.MinValue;UpdateSelection();UpdateMaxState();status.Text="Setup restaurado na prévia. Clique em Aplicar iluminação para enviar.";}
 void ExportDiagnostics(){if(busy)return;using(var dialog=new SaveFileDialog{Title="Exportar diagnóstico",Filter="Arquivo de texto (*.txt)|*.txt",FileName="thebestrgb-diagnostico.txt",AddExtension=true})if(dialog.ShowDialog(this)==DialogResult.OK){try{var text=new StringBuilder();text.AppendLine("ThebestRGB 22");text.AppendLine("Gerado: "+DateTime.Now.ToString("s"));text.AppendLine("Sistema: "+Environment.OSVersion);text.AppendLine("DPI: "+CurrentAutoScaleDimensions.Width+" x "+CurrentAutoScaleDimensions.Height);text.AppendLine("Modo: "+effectMode.Text+" / velocidade "+effectSpeed.Value);text.AppendLine("Perfis: "+profiles.Count);text.AppendLine("Runtime OpenRGB: "+File.Exists(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"runtime","OpenRGB.exe")));for(int i=0;i<cards.Count;i++)text.AppendLine(cards[i].State.Name+" | incluído="+cards[i].State.Included+" | conexão="+connectionLabels[i].Text+" | status="+cards[i].Status.Text);File.WriteAllText(dialog.FileName,text.ToString(),Encoding.UTF8);status.Text="Diagnóstico exportado: "+Path.GetFileName(dialog.FileName)+".";}catch(Exception ex){status.Text="Não foi possível exportar o diagnóstico: "+ex.Message;}}}
 protected override bool ProcessCmdKey(ref Message msg,Keys keyData){if(keyData==saveShortcut){SaveProfile();return true;}if(keyData==undoShortcut){UndoSetup();return true;}if(keyData==verifyShortcut){VerifyDevices();return true;}if(keyData==stopShortcut&&!busy){StopEffect();status.Text="Efeito parado.";return true;}return base.ProcessCmdKey(ref msg,keyData);}
 void ConfigureShortcuts(){using(var dialog=new ShortcutSettingsForm(saveShortcut,undoShortcut,verifyShortcut,stopShortcut)){if(dialog.ShowDialog(this)!=DialogResult.OK)return;saveShortcut=dialog.SaveKey;undoShortcut=dialog.UndoKey;verifyShortcut=dialog.VerifyKey;stopShortcut=dialog.StopKey;shortcutHint.Text=ShortcutText();}}
 void OpenPreferences(){using(var dialog=new PreferencesForm(startupItem.Checked,closeToTrayItem.Checked)){if(dialog.ShowDialog(this)!=DialogResult.OK)return;if(startupItem.Checked!=dialog.StartWithWindows)startupItem.Checked=dialog.StartWithWindows;if(closeToTrayItem.Checked!=dialog.MinimizeOnClose)closeToTrayItem.Checked=dialog.MinimizeOnClose;if(dialog.ConfigureShortcuts)ConfigureShortcuts();status.Text="Preferências atualizadas.";}}
 string ShortcutText(){return FormatKey(saveShortcut)+" salvar  ·  "+FormatKey(undoShortcut)+" desfazer  ·  "+FormatKey(verifyShortcut)+" verificar  ·  "+FormatKey(stopShortcut)+" parar";}
 static string FormatKey(Keys k){return k==Keys.F5?"F5":k==Keys.F6?"F6":k==Keys.Escape?"Esc":k==Keys.F12?"F12":k==(Keys.Control|Keys.S)?"Ctrl+S":k==(Keys.Control|Keys.Shift|Keys.S)?"Ctrl+Shift+S":k==(Keys.Control|Keys.Z)?"Ctrl+Z":k==(Keys.Control|Keys.Y)?"Ctrl+Y":k.ToString();}
 bool IsStartupEnabled(){try{using(var key=Registry.CurrentUser.OpenSubKey("Software\\Microsoft\\Windows\\CurrentVersion\\Run",false))return key!=null&&key.GetValue("ThebestRGB")!=null;}catch{return false;}}
 void SetStartup(bool enabled){try{using(var key=Registry.CurrentUser.OpenSubKey("Software\\Microsoft\\Windows\\CurrentVersion\\Run",true)){if(enabled)key.SetValue("ThebestRGB","\""+Application.ExecutablePath+"\" --tray");else key.DeleteValue("ThebestRGB",false);}status.Text=enabled?"Inicialização com o Windows ativada.":"Inicialização com o Windows desativada.";}catch(Exception ex){status.Text="Não foi possível alterar a inicialização: "+ex.Message;startupItem.Checked=!enabled;}}
 void ApplyTheme(bool light){Color root=light?Color.FromArgb(242,243,248):Color.FromArgb(10,11,15);Color panel=light?Color.White:Color.FromArgb(20,21,27);Color sideColor=light?Color.FromArgb(232,234,241):Color.FromArgb(14,15,19);Color text=light?Color.FromArgb(35,36,45):Color.White;BackColor=root;main.BackColor=root;side.BackColor=sideColor;hero.BackColor=panel;stage.BackColor=light?Color.FromArgb(235,237,244):Color.FromArgb(15,16,21);footer.BackColor=sideColor;foreach(var card in cards){card.BackColor=panel;card.Slider.BackColor=panel;card.Included.ForeColor=text;card.Percent.ForeColor=text;card.Status.ForeColor=light?Color.FromArgb(82,84,98):Muted;}foreach(Control c in main.Controls)if(c is Label)c.ForeColor=text;foreach(Control c in side.Controls)if(c is Label)c.ForeColor=light?Color.FromArgb(82,84,98):Muted;themeItem.Text=light?"Tema escuro":"Tema claro";status.Text=light?"Tema claro aplicado.":"Tema escuro aplicado.";}
}

class ShortcutSettingsForm:Form {
 public Keys SaveKey,UndoKey,VerifyKey,StopKey;
 ComboBox save,undo,verify,stop;
 public ShortcutSettingsForm(Keys s,Keys u,Keys v,Keys p){SaveKey=s;UndoKey=u;VerifyKey=v;StopKey=p;Text="Configurar atalhos";ClientSize=new Size(380,245);StartPosition=FormStartPosition.CenterParent;BackColor=Color.FromArgb(20,21,27);ForeColor=Color.White;Font=new Font("Segoe UI",9);string[] names={"Salvar perfil","Desfazer","Verificar dispositivos","Parar efeito"};ComboBox[] boxes={save=new ComboBox(),undo=new ComboBox(),verify=new ComboBox(),stop=new ComboBox()};Keys[][] values={new[]{Keys.Control|Keys.S,Keys.Control|Keys.Shift|Keys.S},new[]{Keys.Control|Keys.Z,Keys.Control|Keys.Y},new[]{Keys.F5,Keys.F6},new[]{Keys.Escape,Keys.F12}};Keys[] current={s,u,v,p};for(int i=0;i<4;i++){Controls.Add(new Label{Text=names[i],Location=new Point(18,18+i*40),Width=145});boxes[i].DropDownStyle=ComboBoxStyle.DropDownList;boxes[i].SetBounds(175,14+i*40,170,28);foreach(var key in values[i])boxes[i].Items.Add(ThebestRGBKeyName(key));boxes[i].SelectedIndex=Math.Max(0,Array.IndexOf(values[i],current[i]));Controls.Add(boxes[i]);}var ok=ThebestRGB.Button("Salvar",Color.FromArgb(151,119,246));ok.SetBounds(247,190,98,34);Controls.Add(ok);var cancel=ThebestRGB.Button("Cancelar",Color.FromArgb(35,36,45));cancel.SetBounds(135,190,100,34);cancel.DialogResult=DialogResult.Cancel;Controls.Add(cancel);CancelButton=cancel;ok.Click+=delegate{SaveKey=values[0][save.SelectedIndex];UndoKey=values[1][undo.SelectedIndex];VerifyKey=values[2][verify.SelectedIndex];StopKey=values[3][stop.SelectedIndex];DialogResult=DialogResult.OK;Close();};DarkDialogChrome.Attach(this,Text);}
 static string ThebestRGBKeyName(Keys k){return k==Keys.F5?"F5":k==Keys.F6?"F6":k==Keys.Escape?"Esc":k==Keys.F12?"F12":k==(Keys.Control|Keys.Shift|Keys.S)?"Ctrl+Shift+S":k==(Keys.Control|Keys.Y)?"Ctrl+Y":k==(Keys.Control|Keys.Z)?"Ctrl+Z":"Ctrl+S";}
}

class PreferencesForm:Form {
 public bool StartWithWindows,MinimizeOnClose,ConfigureShortcuts;
 public PreferencesForm(bool startup,bool minimize){StartWithWindows=startup;MinimizeOnClose=minimize;Text="ThebestRGB / Preferências";ClientSize=new Size(540,340);MinimumSize=MaximumSize=ClientSize;StartPosition=FormStartPosition.CenterParent;BackColor=Color.FromArgb(20,21,27);ForeColor=Color.White;Font=new Font("Segoe UI",9);MaximizeBox=false;MinimizeBox=false;
  Controls.Add(new Label{Text="Preferências",Location=new Point(24,18),AutoSize=true,Font=new Font("Segoe UI",18,FontStyle.Bold)});Controls.Add(new Label{Text="Defina como o ThebestRGB se comporta no seu computador.",Location=new Point(26,51),AutoSize=true,ForeColor=ThebestRGB.Muted});
  var startupCheck=Option("Iniciar com o Windows","Abre o ThebestRGB minimizado ao entrar na sua conta.",startup,88);var closeCheck=Option("Minimizar ao fechar","O botão X mantém o app ativo na bandeja do sistema.",minimize,150);
  var shortcutPanel=new Panel{Location=new Point(24,212),Size=new Size(492,42),BackColor=Color.FromArgb(30,32,42)};shortcutPanel.Paint+=delegate(object sender,PaintEventArgs e){using(var p=new Pen(Color.FromArgb(61,62,76)))e.Graphics.DrawRectangle(p,0,0,shortcutPanel.Width-1,shortcutPanel.Height-1);};shortcutPanel.Controls.Add(new Label{Text="Atalhos de teclado",Location=new Point(12,6),AutoSize=true,Font=new Font("Segoe UI",9,FontStyle.Bold)});shortcutPanel.Controls.Add(new Label{Text="Salvar, desfazer, verificar e parar efeito.",Location=new Point(12,23),AutoSize=true,ForeColor=ThebestRGB.Muted,Font=new Font("Segoe UI",7)});var shortcuts=ThebestRGB.Button("Configurar",Color.FromArgb(45,48,62));shortcuts.SetBounds(382,5,98,31);shortcutPanel.Controls.Add(shortcuts);shortcuts.Click+=delegate{ConfigureShortcuts=true;};Controls.Add(shortcutPanel);
  var cancel=ThebestRGB.Button("Cancelar",Color.FromArgb(44,46,57));cancel.SetBounds(24,272,112,34);cancel.DialogResult=DialogResult.Cancel;Controls.Add(cancel);var save=ThebestRGB.Button("Salvar preferências",Color.FromArgb(151,119,246));save.ForeColor=Color.FromArgb(18,13,30);save.Font=new Font("Segoe UI",9,FontStyle.Bold);save.SetBounds(340,272,176,34);Controls.Add(save);save.Click+=delegate{StartWithWindows=startupCheck.Checked;MinimizeOnClose=closeCheck.Checked;DialogResult=DialogResult.OK;Close();};CancelButton=cancel;DarkDialogChrome.Attach(this,Text);
 }
 StudioCheckBox Option(string title,string description,bool value,int top){var check=new StudioCheckBox{Text=title,Checked=value,ForeColor=Color.White,Font=new Font("Segoe UI",10,FontStyle.Bold)};check.SetBounds(28,top,230,28);Controls.Add(check);Controls.Add(new Label{Text=description,Location=new Point(58,top+27),Size=new Size(430,20),ForeColor=ThebestRGB.Muted,Font=new Font("Segoe UI",8)});return check;}
}

